# Generated by Django 4.2.21 on 2025-06-06 17:44

from django.db import migrations


def populate_published_at(apps, schema_editor):
    """Initialise le champ published_at pour les articles existants qui sont publiés"""
    Article = apps.get_model('blog', 'Article')
    for article in Article.objects.filter(is_published=True, published_at__isnull=True):
        # Pour les articles déjà publiés, on utilise leur date de création comme date de publication
        article.published_at = article.created_at
        article.save(update_fields=['published_at'])


def reverse_populate_published_at(apps, schema_editor):
    """Fonction inverse - remet published_at à None"""
    Article = apps.get_model('blog', 'Article')
    Article.objects.filter(published_at__isnull=False).update(published_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_published_at'),
    ]

    operations = [
        migrations.RunPython(populate_published_at, reverse_populate_published_at),
    ]
